# Generated by Django 4.1.2 on 2022-10-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
