# Generated by Django 4.1.3 on 2022-11-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
