# Generated by Django 4.1.2 on 2022-11-25 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_cart_count_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(max_length=200)),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='cartdetails',
            options={'verbose_name': 'Элемент деталей корзины', 'verbose_name_plural': 'Детали корзины'},
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
            ],
            options={
                'verbose_name': 'Элемент деталей заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
    ]
