# Generated by Django 4.1.2 on 2022-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_orders_alter_cartdetails_options_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
